[package]
    name         = "nn"
    edition      = "2021"
    rust-version = "1.79"
    license      = "MIT-0"

[dependencies]
    npc_maker  = { path = "../../rust/" }
    serde      = { version = "1.0" }
    serde_json = { version = "1.0" }
